[anim]
datas = []
root_path = 'resources'

[audio]
datas = []
root_path = '..'

[font]
root_path = 'resources'

    [[font.datas]]
    path = 'arial.ttf'

[texture]
root_path = 'resources'

    [[texture.datas]]
    path = 'role.png'

        [texture.datas.Sampler]
        mipmap = false

            [texture.datas.Sampler.filter]
            mag = 9728
            min = 9728

            [texture.datas.Sampler.wrapper]
            borderColor = [ 1.0, 1.0, 1.0, 1.0 ]
            r = 10497
            s = 10497
            t = 10497

[tilesheet]
datas = []
root_path = 'resources'

[timer]
datas = []
root_path = 'resources'