[anim]
datas = []
root_path = './'

[font]
root_path = 'D:\Code\NickelEngine\sandbox\resources'

    [[font.datas]]
    path = 'arial.ttf'

[texture]
root_path = 'D:\Code\NickelEngine\sandbox\resources'

    [[texture.datas]]
    path = 'angle.png'

        [texture.datas.Sampler]
        mipmap = false

            [texture.datas.Sampler.filter]
            mag = 9729
            min = 9729

            [texture.datas.Sampler.wrapper]
            borderColor = [ 1.0, 1.0, 1.0, 1.0 ]
            r = 10497
            s = 10497
            t = 10497

    [[texture.datas]]
    path = 'role.png'

        [texture.datas.Sampler]
        mipmap = false

            [texture.datas.Sampler.filter]
            mag = 9729
            min = 9729

            [texture.datas.Sampler.wrapper]
            borderColor = [ 1.0, 1.0, 1.0, 1.0 ]
            r = 10497
            s = 10497
            t = 10497

[tilesheet]
datas = []
root_path = 'D:\Code\NickelEngine\sandbox\resources'

[timer]
datas = []
root_path = 'D:\Code\NickelEngine\sandbox\resources'